# Generated by Django 4.1.3 on 2022-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('customer', 'customer'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
