# Generated by Django 4.1.3 on 2023-01-03 13:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_employee_name_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('emp_about_description', models.CharField(default='', max_length=255)),
                ('heading', models.CharField(default='', max_length=955)),
                ('saloon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon')),
                ('services_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.services_list')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee_name',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.employee'),
        ),
        migrations.AddField(
            model_name='employee_timing',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.employee'),
        ),
    ]
