# Generated by Django 4.1.3 on 2023-01-12 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('commit', models.CharField(default='', max_length=255)),
                ('star', models.IntegerField(default='0')),
                ('description', models.CharField(default='', max_length=255)),
                ('by_name', models.CharField(default='', max_length=255)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('float_list_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.float_list')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
