# Generated by Django 4.1.3 on 2022-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_role_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelisttoken',
            old_name='account_id',
            new_name='register_id',
        ),
        migrations.RemoveField(
            model_name='whitelisttoken',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='whitelisttoken',
            name='status',
        ),
        migrations.AddField(
            model_name='whitelisttoken',
            name='token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='whitelisttoken',
            name='useragent',
            field=models.TextField(default=''),
        ),
    ]
