# Generated by Django 4.1.3 on 2022-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_rename_account_id_whitelisttoken_register_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
