# Generated by Django 4.1.3 on 2022-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_saloon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='image',
            field=models.ImageField(default='', upload_to='superadmin/'),
        ),
    ]
