# Generated by Django 4.1.3 on 2023-01-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.account'),
        ),
    ]
