# Generated by Django 4.1.3 on 2023-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_employee_employee_name_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=955),
        ),
    ]
