# Generated by Django 4.1.3 on 2023-01-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='superadmin/'),
        ),
    ]
