# Generated by Django 4.1.3 on 2022-11-19 08:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_delete_whitelisttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='whitelistToken',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('token', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_agent', models.TextField(default='')),
                ('register_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.register')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
