# Generated by Django 4.1.3 on 2023-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_remove_review_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='by_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
