# Generated by Django 4.1.3 on 2022-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_whitelisttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
