# Generated by Django 4.1.3 on 2022-12-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_section_column_alter_service_section_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='section_column',
            new_name='float_list',
        ),
    ]
