# Generated by Django 4.1.3 on 2023-01-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_review_by_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='by_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
    ]
