# Generated by Django 4.1.3 on 2022-11-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_role_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('manager', 'manager'), ('customer', 'customer'), ('user', 'user')], default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='whitelistToken',
        ),
    ]
