# Generated by Django 4.1.3 on 2022-12-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_section_column_float_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='section_id',
        ),
        migrations.AddField(
            model_name='float_list',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.category'),
        ),
    ]
