# Generated by Django 4.1.3 on 2023-01-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_remove_review_by_name_remove_review_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='float_list_id',
        ),
    ]
