# Generated by Django 4.1.3 on 2023-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_remove_review_float_list_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='commit',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
