# Generated by Django 4.1.3 on 2023-01-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_remove_review_commit_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='services_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.services_list'),
        ),
    ]
