# Generated by Django 4.1.3 on 2022-12-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_rename_section_name_float_list_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='float_list',
            old_name='service',
            new_name='section_name',
        ),
    ]
