# Generated by Django 4.1.3 on 2022-11-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_remove_whitelisttoken_register_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelisttoken',
            old_name='role',
            new_name='role_name',
        ),
    ]
