# Generated by Django 4.1.3 on 2022-12-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_rename_service_float_list_section_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='float_list',
            name='category_id',
        ),
        migrations.AddField(
            model_name='float_list',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
    ]
