# Generated by Django 4.1.3 on 2022-11-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_rename_role_whitelisttoken_role_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelisttoken',
            old_name='role_name',
            new_name='role',
        ),
    ]
