# Generated by Django 4.1.3 on 2022-12-22 08:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_remove_float_list_category_id_float_list_saloon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='before_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='saloon_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='service_type',
        ),
        migrations.CreateModel(
            name='multiple_category_slider',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category_name', models.CharField(default='', max_length=255)),
                ('before_time', models.TimeField(blank=True, null=True)),
                ('service_type', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default=0)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.category')),
                ('saloon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
