# Generated by Django 4.1.3 on 2023-01-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_review_float_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='float_id',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default='', upload_to='superadmin/'),
        ),
    ]
