# Generated by Django 4.1.3 on 2022-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_rename_role_name_whitelisttoken_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
