# Generated by Django 4.1.3 on 2022-12-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_rename_categoryname_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon_image',
            name='tyype',
            field=models.CharField(default='', max_length=255),
        ),
    ]
