# Generated by Django 4.1.3 on 2022-12-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_saloon_image_tyype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple_category_slider',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='service_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='multiple_category_slider',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.category'),
        ),
    ]
