# Generated by Django 4.1.3 on 2022-11-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_remove_whitelisttoken_role_whitelisttoken_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelisttoken',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
    ]
