# Generated by Django 4.1.3 on 2022-11-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_alter_whitelisttoken_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelisttoken',
            old_name='role_id',
            new_name='rol',
        ),
    ]
