# Generated by Django 4.1.3 on 2023-01-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_rename_category_name_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='service_type',
        ),
    ]
