# Generated by Django 4.1.3 on 2022-11-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_rename_role_id_whitelisttoken_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelisttoken',
            name='rol',
        ),
        migrations.AddField(
            model_name='whitelisttoken',
            name='roleid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.register'),
        ),
    ]
