# Generated by Django 4.1.3 on 2022-11-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_remove_whitelisttoken_rol_whitelisttoken_roleid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelisttoken',
            name='roleid',
        ),
        migrations.AddField(
            model_name='whitelisttoken',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
    ]
