# Generated by Django 4.1.3 on 2022-12-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_rename_multiple_category_slider_services_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_list',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.services_list'),
        ),
    ]
