# Generated by Django 4.1.3 on 2022-11-21 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_remove_whitelisttoken_role_whitelisttoken_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelisttoken',
            name='role_id',
        ),
        migrations.AddField(
            model_name='whitelisttoken',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
    ]
