# Generated by Django 4.1.3 on 2023-01-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_employee_name_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_timing',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.employee_name'),
        ),
    ]
