# Generated by Django 4.1.3 on 2022-11-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_remove_whitelisttoken_role_id_whitelisttoken_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whitelisttoken',
            name='role',
        ),
        migrations.AddField(
            model_name='whitelisttoken',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.register'),
        ),
    ]
