# Generated by Django 4.1.3 on 2022-12-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_remove_category_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
    ]
