# Generated by Django 4.1.3 on 2022-11-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_remove_whitelisttoken_role_whitelisttoken_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role_id',
            new_name='role',
        ),
    ]
