# Generated by Django 4.1.3 on 2023-01-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_employee_timing_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_timing',
            old_name='enddate',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='employee_timing',
            old_name='startdate',
            new_name='starttime',
        ),
        migrations.RemoveField(
            model_name='employee_timing',
            name='employee_id',
        ),
    ]
