# Generated by Django 4.1.3 on 2022-12-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_category_saloon_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services_list',
            old_name='category_name',
            new_name='name',
        ),
    ]
