# Generated by Django 4.1.3 on 2023-01-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_rename_enddate_employee_timing_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_name',
            name='employee_timing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.employee_timing'),
        ),
    ]
