# Generated by Django 4.1.3 on 2022-12-28 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_rename_category_name_services_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon_image',
            name='tyype',
        ),
        migrations.CreateModel(
            name='section_table',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('saloon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
