# Generated by Django 4.1.3 on 2022-11-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_rename_role_register_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saloon',
            old_name='name',
            new_name='saloon_name',
        ),
    ]
