# Generated by Django 4.1.3 on 2022-12-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0023_remove_saloon_image_tyype_section_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section_table',
            name='saloon_id',
        ),
        migrations.AddField(
            model_name='section_table',
            name='by_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='section_table',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section_table',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='section_table',
            name='float_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.float_list'),
        ),
    ]
