# Generated by Django 4.1.3 on 2023-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_remove_employee_name_employee_timing_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_name',
            name='date',
        ),
        migrations.AddField(
            model_name='employee_timing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
