# Generated by Django 4.1.3 on 2022-11-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0024_rename_name_saloon_saloon_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role_id',
            new_name='role',
        ),
    ]
