# Generated by Django 4.1.3 on 2022-12-29 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_portfolio_review_delete_section_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('saloon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='venue_amenitie',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('venue', models.CharField(default='', max_length=255)),
                ('detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='travel_fee_policy',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('discription', models.CharField(default='', max_length=955)),
                ('detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='social_media_share',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('icon_name', models.CharField(default='', max_length=255)),
                ('icon_img', models.ImageField(upload_to='superadmin/')),
                ('detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('discription', models.CharField(default='', max_length=255)),
                ('detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='pay_cancellation_policy',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('discription', models.CharField(default='', max_length=955)),
                ('detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='contact_buss_hour',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_no', models.CharField(default='', max_length=255)),
                ('monday', models.TimeField(blank=True, null=True)),
                ('tuesday', models.TimeField(blank=True, null=True)),
                ('wednesday', models.TimeField(blank=True, null=True)),
                ('thursday', models.TimeField(blank=True, null=True)),
                ('friday', models.TimeField(blank=True, null=True)),
                ('saturday', models.TimeField(blank=True, null=True)),
                ('sunday', models.TimeField(blank=True, null=True)),
                ('detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.detail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='about_us',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('discription', models.CharField(default='', max_length=955)),
                ('contact_buss_hour_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.contact_buss_hour')),
                ('pay_cancellation_policy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.pay_cancellation_policy')),
                ('report_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.report')),
                ('social_media_share_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.social_media_share')),
                ('travel_fee_policy_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.travel_fee_policy')),
                ('venue_amenitie_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.venue_amenitie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
