# Generated by Django 4.1.3 on 2022-11-23 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_rename_role_id_register_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
    ]
