# Generated by Django 4.1.3 on 2022-11-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0026_alter_saloon_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role',
            new_name='role_name',
        ),
        migrations.AlterField(
            model_name='saloon',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.register'),
        ),
    ]
