# Generated by Django 4.1.3 on 2022-12-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_about_us_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='contact_buss_hour_id',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='pay_cancellation_policy_id',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='social_media_share_id',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='travel_fee_policy_id',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='venue_amenitie_id',
        ),
    ]
