# Generated by Django 4.1.3 on 2022-11-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0027_rename_role_register_role_name_alter_saloon_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role_name',
            new_name='role',
        ),
    ]
