# Generated by Django 4.1.3 on 2022-12-30 10:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0029_alter_detail_saloon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_buss_hour',
            name='discription',
            field=models.CharField(default='', max_length=955),
        ),
        migrations.AddField(
            model_name='contact_buss_hour',
            name='heading_1',
            field=models.CharField(default='', max_length=955),
        ),
        migrations.AddField(
            model_name='contact_buss_hour',
            name='icon_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='python manage.py runserver', max_length=255),
        ),
        migrations.CreateModel(
            name='health_safety_rule',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('saloon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
