# Generated by Django 4.1.3 on 2022-11-23 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0030_rename_role_saloon_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.register'),
        ),
    ]
