# Generated by Django 4.1.3 on 2022-11-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0031_alter_saloon_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saloon',
            old_name='role_id',
            new_name='role',
        ),
    ]
