# Generated by Django 4.1.3 on 2022-12-30 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0031_remove_contact_buss_hour_heading_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='contact_buss_hour',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='pay_cancellation_policy',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='social_media_share',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='travel_fee_policy',
            name='detail_id',
        ),
        migrations.RemoveField(
            model_name='venue_amenitie',
            name='detail_id',
        ),
        migrations.AddField(
            model_name='about_us',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
        migrations.AddField(
            model_name='contact_buss_hour',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
        migrations.AddField(
            model_name='pay_cancellation_policy',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
        migrations.AddField(
            model_name='report',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
        migrations.AddField(
            model_name='social_media_share',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
        migrations.AddField(
            model_name='travel_fee_policy',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
        migrations.AddField(
            model_name='venue_amenitie',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
    ]
