# Generated by Django 4.1.3 on 2022-12-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0032_remove_about_us_detail_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us',
            old_name='heading_1',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='contact_buss_hour',
            old_name='heading_2',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='pay_cancellation_policy',
            old_name='heading_6',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='heading_6',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='social_media_share',
            old_name='heading_3',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='travel_fee_policy',
            old_name='heading_5',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='venue_amenitie',
            old_name='heading_4',
            new_name='heading',
        ),
    ]
