# Generated by Django 4.1.3 on 2022-11-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0032_rename_role_id_saloon_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role',
            new_name='role_id',
        ),
        migrations.RenameField(
            model_name='saloon',
            old_name='role',
            new_name='role_id',
        ),
    ]
