# Generated by Django 4.1.3 on 2022-12-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0034_remove_employee_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='heading',
            field=models.CharField(default='', max_length=955),
        ),
    ]
