# Generated by Django 4.1.3 on 2022-11-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0034_alter_saloon_role_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facility',
            new_name='service',
        ),
    ]
