# Generated by Django 4.1.3 on 2022-11-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0037_remove_employee_saloon_id_employee_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon',
            name='Employee_Detail',
        ),
        migrations.AddField(
            model_name='employee',
            name='saloon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.saloon'),
        ),
    ]
