# Generated by Django 4.1.3 on 2022-11-26 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0038_remove_saloon_employee_detail_employee_saloon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.service'),
        ),
    ]
