# Generated by Django 4.1.3 on 2022-11-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0040_employee_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='endfromtime',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='startfromtime',
        ),
        migrations.AddField(
            model_name='service',
            name='startfromtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
