# Generated by Django 4.1.3 on 2022-11-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0041_remove_employee_days_remove_employee_endfromtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='startfromtime',
            new_name='Facility_Timing',
        ),
        migrations.AlterField(
            model_name='package',
            name='packagesStatus',
            field=models.BooleanField(default='False', max_length=255),
        ),
    ]
