# Generated by Django 4.1.3 on 2022-11-28 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0042_rename_startfromtime_service_facility_timing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Facility_Timing',
            new_name='Service_Timing',
        ),
    ]
