# Generated by Django 4.1.3 on 2022-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0044_register_otp_register_otpstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Added_by',
        ),
        migrations.RemoveField(
            model_name='register',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='saloon',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Added_by',
        ),
        migrations.AlterField(
            model_name='register',
            name='oTPStatus',
            field=models.BooleanField(default='False'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
