# Generated by Django 4.1.3 on 2022-12-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0045_remove_employee_added_by_remove_register_role_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='oTP',
        ),
        migrations.RemoveField(
            model_name='register',
            name='oTPStatus',
        ),
    ]
