# Generated by Django 4.1.3 on 2022-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0046_remove_register_otp_remove_register_otpstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='oTP',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='register',
            name='oTPStatus',
            field=models.BooleanField(default='False'),
        ),
    ]
