# Generated by Django 4.1.3 on 2022-12-05 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0047_register_otp_register_otpstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='Added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
        migrations.AddField(
            model_name='register',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saloon',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
        migrations.AddField(
            model_name='service',
            name='Added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.role'),
        ),
    ]
