# Generated by Django 4.1.3 on 2022-12-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0050_account_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saloon',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Added_by',
        ),
        migrations.AddField(
            model_name='saloon',
            name='image',
            field=models.ImageField(default='superadmin/dumm.jpg', upload_to='superadmin/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='superadmin/dumm.jpg', upload_to='superadmin/'),
        ),
    ]
