# Generated by Django 4.1.3 on 2022-12-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0052_rename_description_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='saloon_id',
        ),
        migrations.AddField(
            model_name='saloon',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.service'),
        ),
    ]
