# Generated by Django 4.1.3 on 2022-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0053_remove_service_saloon_id_saloon_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saloon',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
