# Generated by Django 4.1.3 on 2022-12-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0054_saloon_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
