# Generated by Django 4.1.3 on 2022-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0056_service_before_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.AlterField(
            model_name='service',
            name='before_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
